-- One current record per patient; a draft never replaces finalized answers.
ALTER TABLE Pergunta_Anamnese ADD COLUMN IF NOT EXISTS codigo VARCHAR(80);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pergunta_codigo ON Pergunta_Anamnese(codigo);
CREATE UNIQUE INDEX IF NOT EXISTS uq_resposta_paciente_pergunta ON Resposta_Anamnese(id_paciente, id_pergunta);

CREATE TABLE IF NOT EXISTS Anamnese (
    id_paciente INT PRIMARY KEY REFERENCES Paciente(id_paciente),
    versao BIGINT NOT NULL DEFAULT 0,
    rascunho TEXT,
    finalizada_em TIMESTAMP,
    atualizada_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_nutricionista INT NOT NULL REFERENCES Nutricionista(id_nutricionista)
);

INSERT INTO Pergunta_Anamnese (codigo, categoria, texto_pergunta, tipo_resposta, ativo) VALUES
('height', 'Medidas corporais', 'Altura (m)', 'number', TRUE),
('weight', 'Medidas corporais', 'Peso atual (kg)', 'number', TRUE),
('profession', 'Trabalho e contato', 'Profissão', 'text', TRUE),
('phone', 'Trabalho e contato', 'Número/WhatsApp', 'tel', TRUE),
('origin', 'Origem', 'Como chegou até nós?', 'select', TRUE),
('originOther', 'Origem', 'Informe como chegou até nós', 'text', TRUE),
('bodyHealth', 'Relacionamento com Comida e Hábitos', 'Como você se sente em relação ao seu corpo e saúde no dia a dia?', 'textarea', TRUE),
('eatingRoutine', 'Relacionamento com Comida e Hábitos', 'Como está sua rotina alimentar?', 'textarea', TRUE),
('foodPreferences', 'Relacionamento com Comida e Hábitos', 'Quais alimentos ou preparações você gosta, evita ou sente dificuldade em incluir?', 'textarea', TRUE),
('hungerMoments', 'Relacionamento com Comida e Hábitos', 'Em quais momentos você percebe mais fome ou vontade de comer?', 'textarea', TRUE),
('emotions', 'Relacionamento com Comida e Hábitos', 'Como costuma lidar com emoções, ansiedade ou cansaço na alimentação?', 'textarea', TRUE),
('foodRules', 'Relacionamento com Comida e Hábitos', 'Existe algum medo ou regra alimentar que você sente que pesa na sua rotina?', 'textarea', TRUE),
('emotionalHunger', 'Relacionamento com Comida e Hábitos', 'Fome emocional', 'range', TRUE),
('bodySatisfaction', 'Relacionamento com Comida e Hábitos', 'Satisfação corporal', 'range', TRUE),
('mealPleasure', 'Relacionamento com Comida e Hábitos', 'Prazer ao se alimentar', 'range', TRUE),
('typicalDay', 'Rotina Alimentar', 'Conte como costuma ser um dia alimentar típico', 'textarea', TRUE),
('mealsPerDay', 'Rotina Alimentar', 'Quantas refeições faz por dia?', 'number', TRUE),
('eatsOut', 'Rotina Alimentar', 'Costuma fazer refeições fora de casa?', 'select', TRUE),
('diet', 'Rotina Alimentar', 'Tem alguma dieta específica?', 'select', TRUE),
('dietOther', 'Rotina Alimentar', 'Qual dieta específica?', 'text', TRUE),
('supplement', 'Rotina Alimentar', 'Você faz uso de suplementos?', 'select', TRUE),
('supplementDetails', 'Rotina Alimentar', 'Quais suplementos utiliza?', 'text', TRUE),
('improvements', 'Rotina Alimentar', 'Há algo na sua rotina alimentar que gostaria de melhorar?', 'textarea', TRUE),
('diagnoses', 'Histórico de Saúde', 'Diagnóstico atual', 'checkbox', TRUE),
('diagnosisOther', 'Histórico de Saúde', 'Qual diagnóstico?', 'text', TRUE),
('medication', 'Histórico de Saúde', 'Usa medicação atualmente?', 'select', TRUE),
('medicationDetails', 'Histórico de Saúde', 'Quais medicações utiliza?', 'textarea', TRUE),
('allergy', 'Histórico de Saúde', 'Tem alergias?', 'select', TRUE),
('allergyDetails', 'Histórico de Saúde', 'Quais alergias?', 'textarea', TRUE),
('recentExams', 'Histórico de Saúde', 'Possui exames recentes?', 'select', TRUE),
('exam', 'Histórico de Saúde', 'Qual exame?', 'select', TRUE),
('examOther', 'Histórico de Saúde', 'Informe o exame', 'text', TRUE),
('familyHistory', 'Histórico de Saúde', 'Histórico familiar relevante?', 'select', TRUE),
('familyCondition', 'Histórico de Saúde', 'Qual condição?', 'select', TRUE),
('familyConditionOther', 'Histórico de Saúde', 'Informe a condição', 'text', TRUE),
('digestiveHealth', 'Histórico de Saúde', 'Observações sobre saúde digestiva', 'textarea', TRUE),
('urineColor', 'Histórico de Saúde', 'Cor da urina habitual', 'select', TRUE),
('laxative', 'Histórico de Saúde', 'Faz uso de laxantes?', 'select', TRUE),
('laxativeDetails', 'Histórico de Saúde', 'Qual laxante e frequência de uso?', 'text', TRUE),
('bristol', 'Histórico de Saúde', 'Fezes (Escala de Bristol)', 'select', TRUE),
('stoolColor', 'Histórico de Saúde', 'Cor das fezes', 'select', TRUE),
('stoolOdor', 'Histórico de Saúde', 'Odor das fezes', 'select', TRUE),
('evacuationFrequency', 'Histórico de Saúde', 'Regularidade de evacuação', 'select', TRUE),
('physicalActivity', 'Atividade Física', 'Pratica atividade física regularmente?', 'select', TRUE),
('activities', 'Atividade Física', 'Tipo de atividade', 'checkbox', TRUE),
('activityOther', 'Atividade Física', 'Qual atividade?', 'text', TRUE),
('weeklyFrequency', 'Atividade Física', 'Frequência semanal', 'select', TRUE),
('intensity', 'Atividade Física', 'Intensidade', 'select', TRUE),
('sleepHours', 'Sono e Estresse', 'Quantas horas de sono costuma ter por noite?', 'select', TRUE),
('rested', 'Sono e Estresse', 'Sente-se descansado(a) ao acordar?', 'select', TRUE),
('stressed', 'Sono e Estresse', 'Sente-se frequentemente estressado(a)?', 'select', TRUE),
('objectives', 'Objetivos e Expectativas', 'Quais seus principais objetivos?', 'checkbox', TRUE),
('objectiveOther', 'Objetivos e Expectativas', 'Qual objetivo?', 'text', TRUE),
('previousAttempts', 'Objetivos e Expectativas', 'Já tentou alcançar esses objetivos antes? Como foi?', 'textarea', TRUE),
('deadline', 'Objetivos e Expectativas', 'Possui prazo para atingir seus objetivos?', 'select', TRUE),
('deadlineReason', 'Objetivos e Expectativas', 'Por que esse prazo é importante?', 'textarea', TRUE),
('finalNotes', 'Considerações finais', 'Existe algo mais que gostaria de compartilhar sobre hábitos ou saúde?', 'textarea', TRUE)
ON CONFLICT (codigo) DO NOTHING;
