api.security.token.secret=${JWT_SECRET}

email.provider=smtp
app.email.auto-confirm=false

spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAILTRAP_USERNAME:}
spring.mail.password=${MAILTRAP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
